
[DatabaseLog,                                                                            
AdventureWorksDWBuildVersion,                                                                               
DimAccount                                    ,                                                                               
DimCurrency                                   ,                                                                               
DimCustomer                                   ,                                                                               
DimDate                                       ,                                                                               
DimDepartmentGroup                            ,                                                                               
DimEmployee                                   ,                                                                                
DimGeography                                  ,                                                                                
DimOrganization                               ,                                                                                
DimProduct                                    ,                                                                                
DimProductCategory                            ,                                                                                
DimProductSubcategory                         ,                                                                                
DimPromotion                                  ,                                                                                
DimReseller                                   ,                                                                                
DimSalesReason                                ,                                                                                
DimSalesTerritory                             ,                                                                                
DimScenario                                   ,                                                                                
FactAdditionalInternationalProductDescription ,                                                                                
FactCallCenter                                ,                                                                                
FactCurrencyRate                              ,                                                                                
FactFinance                                   ,                                                                                
FactInternetSales                             ,                                                                                
FactInternetSalesReason                       ,                                                                                
FactProductInventory                          ,                                                                                
FactResellerSales                             ,                                                                                
FactSalesQuota                                ,                                                                                
FactSurveyResponse                            ,                                                                                
NewFactCurrencyRate                           ,                                                                                
ProspectiveBuyer                              ,                                                                                
sysdiagrams]